-- insert into system.tree_registry (
--   tree_key,
--   schema_name,
--   table_name
-- )
-- values
-- (
--   'organizations',
--   'public',
--   'organizations'
-- ),
-- (
--   'project_catalog_std',
--   'public',
--   'project_catalog_std'
-- )
-- on conflict (tree_key) do nothing;