import EventEmitter from 'events';

const bus = new EventEmitter();

// Publish an event to a named topic. Listeners should subscribe to `event:<topic>`.
export const publishEvent = (topic, event) => {
    process.nextTick(() => bus.emit(`event:${topic}`, event));
};

// Create and validate helpers for canonical event shape
export const createEvent = (topic, { canonicalKey, ringNo, paramCode, value, range, windowMs, severity, message, timestamp, payload } = {}) => {
    const ev = {
        canonicalKey: canonicalKey ?? null,
        ringNo: ringNo ?? null,
        paramCode: paramCode ?? null,
        value: value ?? null,
        range: range ?? null,
        windowMs: windowMs ?? 0,
        timestamp: timestamp ?? new Date().toISOString(),
        message: message ?? null,
        topic,
        severity: severity ?? 'info',
        payload: payload ?? {},
    };
    const err = validateEvent(ev);
    if (err) throw new Error(`Invalid event: ${err}`);
    return ev;
};

export const validateEvent = (ev) => {
    if (!ev) return 'event is null or undefined';
    // canonicalKey should be present and represent the canonicalKey used by the system;
    // tbmId is optional but recommended when available for DB correlation.    
    if (!ev.canonicalKey && ev.canonicalKey !== 0) return 'missing canonicalKey';
    if (!ev.ringNo && ev.ringNo !== 0) return 'missing ringNo';
    if (!ev.timestamp) return 'missing timestamp';
    // message is optional; it may be generated by persistence/processing listeners
    return null;
};

// Expose the bus so other modules can subscribe directly if needed
export const getBus = () => bus;

// Helper to initialize multiple listener initializers
export const initEventBus = (initializers = [], opts = {}) => {
    for (const init of initializers) {
        try {
            init(bus, opts);
        } catch (err) {
            console.error('[eventBus] initializer failed:', err);
        }
    }
};

export default bus;
