
INSERT INTO "public"."master_definitions" ("name", "key")
VALUES 
    ('主数据字典','DICT_MASTER'),
    ('工号类型', 'PROJECT_CATALOG_TYPE'),
    ('是否', 'WHETHER'),
    ('工程专业', 'PROJECT_MAJOR'),
    ('客商性质', 'CUSTOMER_NATURE'),
    ('承包模式', 'CONTRACT_CODE'),
    ('所属区域', 'REGION'),
    ('业务板块', 'BUSINESS'),
    ('工程类型', 'PROJECT_TYPE'),
    ('工程性质', 'ENGINEERING_NATURE'),
    ('合同主体', 'USE_QUALIFICATION'),
    ('性别', 'GENDER'),
    ('人员类别', 'PERSON_TYPE'),
    ('岗位', 'JOB_TITLE'),
    ('项目状态', 'PROJECT_STATUS'),
    ('项目性质', 'PROJECT_NATURE'),
    ('组织类别', 'ORG_CATEGORY'),
    ('文化程度', 'EDU_LEVEL'),
    ('外部单位类型', 'EXT_UNIT_TYPE'),
    ('机构负责人', 'ORG_LEADER_ROLE'),
    ('产系统字典',  'DICT_PRODUCTION'),
    ('项目管控级别', 'PROJECT_CONTROL_LEVEL'),
    ('项目风险等级', 'PROJECT_RISK_LEVEL'),
    ('项目子状态', 'PROJECT_SUB_STATUS'),
    ('方案专业', 'PROGRAM_MAJOR'),
    ('工程子类别', 'ENGINEERING_SUBCATEGORY'),
    ('项目关注类别', 'PROJECT_FOCUS_CATEGORY'),
    ('项目关注子类别', 'PROJECT_FOCUS_SUBCATEGORY'),
    ('工点类型', 'PROJECT_WORK_POINT_TYPE'),
    ('危大工程类型', 'DANGEROU_LARGE_PRO_TYPE'),
    ('工号施工状态', 'PROJECT_WORK_POINT_STATUS'),
    ('技术系统字典', 'DICT_TECHNICAL'),
    ('械系统字典', 'DICT_MECHANICAL'),
    ('设备状态', 'EQUIPMENT_STATUS'),
    ('设备来源类型', 'MECH_SOURCE_TYPE'),
    ('报警规则类型', 'TBM_RULE_TYPE'),
    ('盾构机类型', 'TBM_TYPE'),
    ('盾构机业务状态', 'TBM_OPERATION_STATUS'),
    ('安全系统字典', 'DICT_SAFETY'),
    ('物资系统字典', 'DICT_MATERIAL'),
    ('成本系统字典', 'DICT_COST'),
    ('业主单位性质', 'OWNER_NATURE'),
    ('财务系统字典', 'DICT_FINANCE')
ON CONFLICT (key) DO NOTHING;

